Repository ft-transcendence-project/42-transcendence, pull requests merged in 2024-11, with the labels that each got.

#14 [add] login pageを追加
  web/accounts/__init__.py
  web/accounts/admin.py
  web/accounts/apps.py
  web/accounts/migrations/__init__.py
  web/accounts/models.py
  web/accounts/templates/accounts/login.html
  web/accounts/templates/base.html
  web/accounts/tests.py
  web/accounts/urls.py
  web/accounts/views.py
  web/core/settings.py
  web/core/urls.py
Labels: frontend

#10 [add] .pre-commit-configを追加
  .gitignore
  .pre-commit-config.yaml
Labels: settings

#12 [add] djangoとpostgresqlのセットアップを行うdocker_composeの追加
  .env_template
  .gitignore
  docker-compose.yml
  playground/eito/djangotutorial/manage.py
  playground/eito/djangotutorial/mysite/__init__.py
  playground/eito/djangotutorial/mysite/asgi.py
  playground/eito/djangotutorial/mysite/settings.py
  playground/eito/djangotutorial/mysite/urls.py
  playground/eito/djangotutorial/mysite/wsgi.py
  playground/eito/djangotutorial/polls/__init__.py
  playground/eito/djangotutorial/polls/admin.py
  playground/eito/djangotutorial/polls/apps.py
  playground/eito/djangotutorial/polls/migrations/0001_initial.py
  playground/eito/djangotutorial/polls/migrations/__init__.py
  playground/eito/djangotutorial/polls/models.py
  playground/eito/djangotutorial/polls/static/polls/style.css
  playground/eito/djangotutorial/polls/templates/polls/detail.html
  playground/eito/djangotutorial/polls/templates/polls/index.html
  playground/eito/djangotutorial/polls/templates/polls/results.html
  playground/eito/djangotutorial/polls/tests.py
  playground/eito/djangotutorial/polls/urls.py
  playground/eito/djangotutorial/polls/views.py
  playground/eito/djangotutorial/templates/base_site.html
  requirements.txt
  web/Dockerfile
  web/accounts/__init__.py
  web/accounts/admin.py
  web/accounts/apps.py
  web/accounts/migrations/__init__.py
  web/accounts/models.py
  web/accounts/templates/accounts/login.html
  web/accounts/templates/base.html
  web/accounts/tests.py
  web/accounts/urls.py
  web/accounts/views.py
  web/core/__init__.py
  web/core/asgi.py
  web/core/settings.py
  web/core/urls.py
  web/core/wsgi.py
  web/manage.py
  web/requirements.txt
Labels: backend

#23 [add] homepageを作成しました
  playground/eito/Django/use_jwt/use_jwt/urls.py
  web/core/settings.py
  web/core/urls.py
  web/homepage/__init__.py
  web/homepage/admin.py
  web/homepage/apps.py
  web/homepage/migrations/__init__.py
  web/homepage/models.py
  web/homepage/templates/homepage/homepage.html
  web/homepage/tests.py
  web/homepage/views.py
Labels: frontend

#16 [add] login pageのbackendを実装しました
  web/accounts/templates/accounts/login.html
  web/accounts/templates/base.html
  web/accounts/tests.py
Labels: backend, accounts

#32 [add] GithubActionsを追加
  .github/workflows/docker-compose-web-test.yml
  .gitignore
Labels: settings, test

#30 [add] TournamentページのUI作成
  web/core/settings.py
  web/matches/__init__.py
  web/matches/admin.py
  web/matches/apps.py
  web/matches/migrations/__init__.py
  web/matches/models.py
  web/matches/static/matches/css/style.css
  web/matches/templates/matches/matches.html
  web/matches/tests.py
  web/matches/views.py
  web/tournament/templates/tournament/tournament.html
  web/tournament/urls.py
Labels: frontend

#31 [update] OTP認証に対するテスト追加
  web/accounts/tests.py
  web/requirements.txt
Labels: backend, accounts, test

#26 [implement] OneTimePasswordを用いた2FAを実装しました
  .github/workflows/docker-compose-web-test.yml
  .gitignore
  docker-compose.yml
  web/Dockerfile
  web/accounts/admin.py
  web/accounts/migrations/0001_initial.py
  web/accounts/models.py
  web/accounts/templates/accounts/already_setup_otp.html
  web/accounts/templates/accounts/login.html
  web/accounts/templates/accounts/setup_otp.html
  web/accounts/templates/accounts/verify_otp.html
  web/accounts/tests.py
  web/accounts/urls.py
  web/accounts/views.py
  web/core/settings.py
  web/requirements.txt
  web/wait-for-it.sh
Labels: frontend, backend

#34 [add] SignUpページを作成
  docker-compose.yml
  web/accounts/forms.py
  web/accounts/templates/accounts/login.html
  web/accounts/templates/accounts/signup.html
  web/accounts/tests.py
  web/accounts/urls.py
  web/accounts/views.py
Labels: frontend, backend, accounts

#41 [update] バナーをつけて各ページを繋げた
  web/accounts/templates/accounts/login.html
  web/accounts/templates/base.html
  web/accounts/tests.py
  web/accounts/urls.py
  web/accounts/views.py
  web/core/urls.py
  web/gameplay/tests.py
  web/gameplay/urls.py
  web/gameplay/views.py
  web/homepage/templates/homepage/homepage.html
  web/homepage/tests.py
  web/homepage/views.py
  web/tournament/templates/tournament/tournament.html
  web/tournament/urls.py
  web/tournament/views.py
Labels: frontend, backend

#54 [add] NginxとGunicornを導入し、本番環境用のdocker-composeを用意
  .github/workflows/docker-compose-web-prod-test.yml
  .gitignore
  docker-compose.prod.yml
  docker-compose.yml
  nginx/default.conf
  web/entrypoint.sh
  web/requirements.txt
Labels: server
